/*
 * Vitalora ESP32-S3 Smartwatch Firmware
 * Using LVGL for UI rendering on Waveshare 1.47" LCD
 * SVG mockup → SquareLine Studio → LVGL C code
 */

#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <Arduino_GFX_Library.h>
#include <Wire.h>
#include <Adafruit_FT6206.h>
#include <lvgl.h>
#include "lv_port_disp.h"
#include "lv_port_indev.h"

// ==================== Display Configuration ====================
#define GFX_BL 46      // Backlight pin
#define LCD_RST 40     // LCD Reset pin

// ==================== GPIO Configuration ====================
#define PIN_LED 38          // Built-in LED on ESP32-S3
#define PIN_BUTTON 0        // Boot button for testing

// ==================== WiFi Configuration ====================
const char* SSID = "YOUR_SSID";
const char* PASSWORD = "YOUR_PASSWORD";

// ==================== Global Objects ====================
WebServer server(80);

// Arduino_GFX for display (ST7789)
Arduino_DataBus *bus = new Arduino_ESP32SPI(
  45 /* DC */, 21 /* CS */, 38 /* SCK */, 39 /* MOSI */, -1 /* MISO */
);

Arduino_GFX *gfx = new Arduino_ST7789(
  bus, 47 /* RST */, 0 /* rotation */, false /* IPS */,
  172 /* width */, 320 /* height */,
  34 /* col_offset1 */, 0 /* row_offset1 */,
  34 /* col_offset2 */, 0 /* row_offset2 */
);

// FT6206 for touch input
Adafruit_FT6206 ts = Adafruit_FT6206();

// ==================== Timing Configuration ====================
unsigned long lastBlink = 0;
const unsigned long BLINK_INTERVAL = 1000;
unsigned long lastLVGLUpdate = 0;
const unsigned long LVGL_UPDATE_INTERVAL = 5;  // Update LVGL every 5ms

// ==================== Forward Declarations ====================
void setupGPIO();
void setupDisplay();
void setupWiFi();
void setupWebServer();
void setupTouch();
void blinkLED();
void handleRoot();
void handleStatus();
void sendHealthData();

// ==================== Setup ====================
void setup()
{
  Serial.begin(115200);
  delay(1000);

  Serial.println("\n\n");
  Serial.println("╔════════════════════════════════════════════════╗");
  Serial.println("║  Vitalora ESP32-S3 Smartwatch Firmware v5.0    ║");
  Serial.println("║  Using LVGL + Arduino_GFX                      ║");
  Serial.println("║  Waveshare ESP32-S3 Touch LCD 1.47\"            ║");
  Serial.println("╚════════════════════════════════════════════════╝");
  Serial.println();

  setupGPIO();
  Serial.println("[OK] GPIO initialized");

  setupDisplay();
  Serial.println("[OK] Display initialized");

  setupTouch();
  Serial.println("[OK] Touch initialized");

  // Initialize LVGL
  lv_init();
  Serial.println("[OK] LVGL core initialized");

  // Initialize LVGL display driver (uses Arduino_GFX as backend)
  lv_port_disp_init();
  Serial.println("[OK] LVGL display driver initialized");

  // Initialize LVGL input device driver (uses FT6206 as backend)
  lv_port_indev_init();
  Serial.println("[OK] LVGL input device initialized");

  // TODO: Load UI from SquareLine Studio export
  // ui_init(); // This will be generated by SquareLine Studio

  // For now, show a simple test screen
  lv_obj_t *scr = lv_scr_act();
  lv_obj_set_style_bg_color(scr, lv_color_hex(0x000000), LV_PART_MAIN);

  // Add label "LVGL Ready"
  lv_obj_t *label = lv_label_create(scr);
  lv_label_set_text(label, "LVGL Ready!\n\nUse SquareLine\nStudio to\ndesign UI");
  lv_obj_align(label, LV_ALIGN_CENTER, 0, 0);
  lv_obj_set_style_text_color(label, lv_color_hex(0x00AEEF), LV_PART_MAIN);
  lv_obj_set_style_text_font(label, &lv_font_montserrat_16, LV_PART_MAIN);

  setupWiFi();
  Serial.println("[OK] WiFi initialized");

  setupWebServer();
  Serial.println("[OK] Web server initialized");

  Serial.println("[INFO] Firmware ready! LVGL display active...");
}

// ==================== Main Loop ====================
void loop()
{
  // Handle web server requests
  server.handleClient();

  // Blink LED indicator
  blinkLED();

  // Update LVGL with current timing
  unsigned long now = millis();
  if (now - lastLVGLUpdate >= LVGL_UPDATE_INTERVAL) {
    lastLVGLUpdate = now;
    lv_timer_handler();  // LVGL internal timer handler
  }

  delay(1);  // Prevent blocking, allow other tasks
}

// ==================== GPIO Setup ====================
void setupGPIO()
{
  pinMode(PIN_LED, OUTPUT);
  pinMode(PIN_BUTTON, INPUT_PULLUP);
  pinMode(GFX_BL, OUTPUT);

  digitalWrite(PIN_LED, LOW);
  digitalWrite(GFX_BL, HIGH);  // Backlight ON

  Serial.println("[GPIO] LED, button, and backlight configured");
}

// ==================== Display Setup ====================
void setupDisplay()
{
  // LCD Reset sequence
  pinMode(LCD_RST, OUTPUT);
  digitalWrite(LCD_RST, LOW);
  delay(100);
  digitalWrite(LCD_RST, HIGH);
  delay(100);

  // Initialize GFX display
  gfx->begin();
  gfx->setRotation(1);  // Portrait mode (320x172 rotated)
  gfx->fillScreen(0x0000);  // Black screen initially

  Serial.println("[Display] ST7789 initialized successfully!");
  Serial.println("[Display] Resolution: 172×320 (rotated)");
}

// ==================== Touch Setup ====================
void setupTouch()
{
  Wire.begin(19, 20);  // SDA=19, SCL=20 (Waveshare standard I2C pins)

  if (!ts.begin(40)) {  // 40 is the I2C address for FT6206
    Serial.println("[Touch] FT6206 not found, continuing without touch...");
  } else {
    Serial.println("[Touch] FT6206 initialized successfully!");
  }
}

// ==================== WiFi Setup ====================
void setupWiFi()
{
  Serial.print("[WiFi] Connecting to SSID: ");
  Serial.println(SSID);

  WiFi.mode(WIFI_STA);
  WiFi.begin(SSID, PASSWORD);

  int attempts = 0;
  while (WiFi.status() != WL_CONNECTED && attempts < 20) {
    delay(500);
    Serial.print(".");
    attempts++;
  }
  Serial.println();

  if (WiFi.status() == WL_CONNECTED) {
    Serial.print("[WiFi] Connected! IP: ");
    Serial.println(WiFi.localIP());
  } else {
    Serial.println("[WiFi] Failed to connect - using AP mode");
    WiFi.mode(WIFI_AP);
    WiFi.softAP("Vitalora-Watch", "12345678");
    Serial.println("[WiFi] AP Mode: Vitalora-Watch (192.168.4.1)");
  }
}

// ==================== Web Server Setup ====================
void setupWebServer()
{
  server.on("/", handleRoot);
  server.on("/status", handleStatus);
  server.on("/health", HTTP_GET, sendHealthData);

  server.begin();
  Serial.println("[WebServer] Started on port 80");
}

// ==================== HTTP Handlers ====================
void handleRoot()
{
  String html = "<html><head><title>Vitalora Watch</title>";
  html += "<meta name='viewport' content='width=device-width, initial-scale=1'>";
  html += "<style>";
  html += "body { font-family: Arial; margin: 20px; background: #f0f0f0; }";
  html += ".container { max-width: 600px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }";
  html += ".status { padding: 10px; margin: 10px 0; background: #e3f2fd; border-left: 4px solid #2196F3; }";
  html += "button { background: #4CAF50; color: white; padding: 10px 20px; border: none; cursor: pointer; border-radius: 4px; }";
  html += "button:hover { background: #45a049; }";
  html += "</style></head><body>";
  html += "<div class='container'>";
  html += "<h1>Vitalora Smartwatch</h1>";
  html += "<div class='status'><strong>Status:</strong> Online (LVGL)</div>";
  html += "<div class='status'><strong>Device:</strong> Waveshare ESP32-S3 Touch LCD 1.47\"</div>";
  html += "<button onclick='location.href=\"/status\"'>Check Status</button>&nbsp;";
  html += "<button onclick='location.href=\"/health\"'>Get Health Data</button>";
  html += "</div></body></html>";

  server.send(200, "text/html", html);
}

void handleStatus()
{
  String json = "{";
  json += "\"device\":\"ESP32-S3\",";
  json += "\"uptime\":" + String(millis() / 1000) + ",";
  json += "\"wifi_ssid\":\"" + String(WiFi.SSID()) + "\",";
  json += "\"signal_strength\":" + String(WiFi.RSSI()) + ",";
  json += "\"heap_free\":" + String(ESP.getFreeHeap()) + ",";
  json += "\"heap_total\":" + String(ESP.getHeapSize()) + ",";
  json += "\"ui_framework\":\"LVGL 8.3.11\"";
  json += "}";

  server.send(200, "application/json", json);
}

void sendHealthData()
{
  String json = R"({
    "timestamp": 1234567890,
    "heart_rate": 72,
    "temperature": 36.8,
    "steps": 1250,
    "sleep_quality": 85,
    "battery": 95
  })";

  server.send(200, "application/json", json);
}

// ==================== LED Blink ====================
void blinkLED()
{
  unsigned long now = millis();
  if (now - lastBlink >= BLINK_INTERVAL) {
    lastBlink = now;
    digitalWrite(PIN_LED, !digitalRead(PIN_LED));
  }
}
